---
- name: Install Docker and Jenkins on localhost
  hosts: localhost
  become: true

  tasks:
    # Install Docker

    - name: Update APT package index
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install dependencies for Docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    # Install Jenkins

    - name: Install Java (required for Jenkins)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        dest: /usr/share/keyrings/jenkins.gpg

    - name: Add Jenkins APT repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary/
        state: present
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is running
      service:
        name: jenkins
        state: started
        enabled: true
